runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: static/index.html
  upload: static/index\.html
  login: required

- url: /contact/.*
  static_files: static/index.html
  upload: static/index\.html

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /css
  static_dir: static/css

- url: /js
  static_dir: static/js

- url: /contacts
  script: cm.app.api
  login: required

- url: /contacts/.*
  script: cm.app.api
  login: required

- url: /logout
  script: cm.app.api

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?.*\.bak$
- ^package\.json$
- ^package-lock\.json$
- ^webpack\.config\.js$
- client/
- data/
- node_modules/
- tests/
- util/
