export const AUTH0_LOGIN_REQUEST = 'AUTH0_LOGIN_REQUEST'
export const AUTH0_LOGIN_FAILURE = 'AUTH0_LOGIN_FAILURE'
export const AUTH0_LOGIN_SUCCESS = 'AUTH0_LOGIN_SUCCESS'
export const AUTH0_LOGOUT = 'AUTH0_LOGOUT'