export default {
  CONTACTS_SET_CONTACT: 'CONTACTS_SET_CONTACT',
  CONTACTS_ALL_REQUEST: 'CONTACTS_ALL_REQUEST',
  CONTACTS_ALL_FAILURE: 'CONTACTS_ALL_FAILURE',
  CONTACTS_ALL_SUCCESS: 'CONTACTS_ALL_SUCCESS',
  CONTACTS_GET_REQUEST: 'CONTACTS_GET_REQUEST',
  CONTACTS_GET_FAILURE: 'CONTACTS_GET_FAILURE',
  CONTACTS_GET_SUCCESS: 'CONTACTS_GET_SUCCESS',
  CONTACTS_ADD_REQUEST: 'CONTACTS_ADD_REQUEST',
  CONTACTS_ADD_FAILURE: 'CONTACTS_ADD_FAILURE',
  CONTACTS_ADD_SUCCESS: 'CONTACTS_ADD_SUCCESS',
  CONTACTS_UPD_REQUEST: 'CONTACTS_UPD_REQUEST',
  CONTACTS_UPD_FAILURE: 'CONTACTS_UPD_FAILURE',
  CONTACTS_UPD_SUCCESS: 'CONTACTS_UPD_SUCCESS',
  CONTACTS_DEL_REQUEST: 'CONTACTS_DEL_REQUEST',
  CONTACTS_DEL_FAILURE: 'CONTACTS_DEL_FAILURE',
  CONTACTS_DEL_SUCCESS: 'CONTACTS_DEL_SUCCESS'
}
