FORMAT: 1A
HOST: http://localhost:8080/api/contacts

# Contact Manager
Aurelia Contact Manager Tutorial

# Unnammed Endpoint [/]

## Unnammed Endpoint [GET]
list of contacts

+ Response 200 (application/json)

        A JSON message and array of contacts

    + Attributes (Unnammed EndpointResponse)


## Unnammed Endpoint [POST]

+ Request (application/json)
    + Attributes (Contact)


+ Response 200 (application/json)

        contact created

    + Attributes (Unnammed EndpointResponse5)



# By ContactId [/{contactId}]

+ Parameters
    + contactId (string, required)

        contact id


## ByContactId [GET]

+ Response 200 (application/json)

        requested contact

    + Attributes (Contact)


## ByContactId [DELETE]

+ Response 200 (application/json)

        contact deleted

    + Attributes (ByContactIdResponse)


## ByContactId [PATCH]

+ Response 200 (application/json)

        updated contact

    + Attributes (ByContactIdResponse7)



# Data Structures

## Contact (object)


### Properties
+ `_id` (string, optional) - MongoDB contact id
+ `first` (string, optional) - first name
+ `last` (string, optional) - last name
+ `email` (string, optional) - email address
+ `phone` (string, optional) - phone number


## DeleteResult (object)


### Properties
+ `acknowledged` (boolean, optional) 
+ `deleted_count` (number, optional) 


## InsertOneResult (object)


### Properties
+ `acknowledged` (boolean, optional) 
+ `inserted_id` (string, optional) 


## UpdateResult (object)


### Properties
+ `acknowledged` (boolean, optional) 
+ `matched_count` (number, optional) 
+ `modified_count` (number, optional) 
+ `updated_id` (string, optional) 


## Unnammed EndpointResponse (object)


### Properties
+ `message` (string, optional) 
+ `contacts` (array[Contact], optional) 


## Unnammed EndpointResponse5 (object)


### Properties
+ `message` (string, optional) 
+ `obj` (InsertOneResult, optional) 


## ByContactIdResponse (object)


### Properties
+ `message` (string, optional) 
+ `result` (DeleteResult, optional) 


## ByContactIdResponse7 (object)


### Properties
+ `message` (string, optional) 
+ `obj` (Contact, optional) 
+ `result` (UpdateResult, optional) 

