openapi: 3.0.0
info:
  title: Contact Manager
  description: Aurelia Contact Manager Tutorial
  version: 0.0.1
servers:
- url: http://localhost/api/contacts
  variables: {}
paths:
  /:
    get:
      summary: Unnammed Endpoint
      description: list of contacts
      operationId: UnnammedEndpoint
      parameters: []
      responses:
        200:
          description: A JSON message and array of contacts
          content:
            application/json:
              schema:
                description: A JSON message and array of contacts
                $ref: '#/components/schemas/UnnammedEndpointresponse'
      deprecated: false
      security: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    post:
      summary: Unnammed Endpoint
      operationId: UnnammedEndpoint1
      parameters: []
      requestBody:
        description: The contact JSON you want to post
        content:
          application/json:
            schema:
              description: The contact JSON you want to post
              $ref: '#/components/schemas/Contact'
        required: true
      responses:
        200:
          description: contact created
          content:
            application/json:
              schema:
                description: contact created
                $ref: '#/components/schemas/UnnammedEndpointresponse5'
      deprecated: false
      security: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
  /{contactId}:
    get:
      summary: ByContactId
      operationId: ByContactId
      parameters:
      - name: contactId
        in: path
        description: contact id
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        200:
          description: requested contact
          content:
            application/json:
              schema:
                description: requested contact
                $ref: '#/components/schemas/Contact'
      deprecated: false
      security: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    delete:
      summary: ByContactId
      operationId: ByContactId1
      parameters:
      - name: contactId
        in: path
        description: MongoDB contact id
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        200:
          description: contact deleted
          content:
            application/json:
              schema:
                description: contact deleted
                $ref: '#/components/schemas/ByContactIdResponse'
      deprecated: false
      security: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
    patch:
      summary: ByContactId
      operationId: ByContactId2
      parameters:
      - name: contactId
        in: path
        description: MongoDB contact id
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        200:
          description: updated contact
          content:
            application/json:
              schema:
                description: updated contact
                $ref: '#/components/schemas/ByContactIdResponse7'
      deprecated: false
      security: []
      x-operation-settings:
        CollectParameters: false
        AllowDynamicQueryParameters: false
        AllowDynamicFormParameters: false
        IsMultiContentStreaming: false
components:
  schemas:
    Contact:
      title: Contact
      type: object
      properties:
        _id:
          type: string
          description: MongoDB contact id
        first:
          type: string
          description: first name
        last:
          type: string
          description: last name
        email:
          type: string
          description: email address
        phone:
          type: string
          description: phone number
    DeleteResult:
      title: DeleteResult
      type: object
      properties:
        acknowledged:
          type: boolean
        deleted_count:
          type: integer
          format: int32
    InsertOneResult:
      title: InsertOneResult
      type: object
      properties:
        acknowledged:
          type: boolean
        inserted_id:
          type: string
    UpdateResult:
      title: UpdateResult
      type: object
      properties:
        acknowledged:
          type: boolean
        matched_count:
          type: integer
          format: int32
        modified_count:
          type: integer
          format: int32
        updated_id:
          type: string
    UnnammedEndpointresponse:
      title: Unnammed EndpointResponse
      type: object
      properties:
        message:
          type: string
        contacts:
          type: array
          items:
            $ref: '#/components/schemas/Contact'
          description: ''
    UnnammedEndpointresponse5:
      title: Unnammed EndpointResponse5
      type: object
      properties:
        message:
          type: string
        obj:
          $ref: '#/components/schemas/InsertOneResult'
    ByContactIdResponse:
      title: ByContactIdResponse
      type: object
      properties:
        message:
          type: string
        result:
          $ref: '#/components/schemas/DeleteResult'
    ByContactIdResponse7:
      title: ByContactIdResponse7
      type: object
      properties:
        message:
          type: string
        obj:
          $ref: '#/components/schemas/Contact'
        result:
          $ref: '#/components/schemas/UpdateResult'
